CSRF_ENABLED = True
DROP_ALL = False

SERVICE_URL = '访问域名'

WEIXIN_APPID = '微信appid'
WEIXIN_SECRET = '微信secret'

QINIU_AK = '七牛appkey'
QINIU_SK = '七牛secretkey'
BUCKET = '空间名'
BASE_URL = '空间地址'

SECRET_KEY = '网站地址'
UPLOAD_TEMP = '/var/www/FlaskApp/FlaskApp/static/temp'
SQLALCHEMY_DATABASE_URI = '数据库地址'
SQLALCHEMY_POOL_SIZE = 50
SQLALCHEMY_POOL_TIMEOUT = 10
SQLALCHEMY_TRACK_MODIFICATIONS = True
WHOOSH_BASE = 'searchindex'
MAX_SEARCH_RESULTS = 20